spring.application.name=url-shortner2

spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener
spring.datasource.username=postgres
spring.datasource.password=Replicate#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework=DEBUG
logging.level.com.urlshortner.url_shortner2=DEBUG

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379